version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  crawler: 
    build:
      context: ./services/crawler
      dockerfile: Dockerfile
    environment:
      - JSON_PATH=/app/configs/
    ports:
      - "8000"

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CRAWLER_ADDRESS=crawler:8000
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200/
      - JSON_PATH=/app/configs/
    depends_on:
      - crawler
      - elasticsearch
    entrypoint:
      [
        # "/app/wait-for.sh",
        # "elasticsearch:9200",
        # "--",
        "/app/main"
      ]

