version: '3.9'
services:
  postgres: 
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=footballnews
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  crawler: 
    build:
      context: ./services/crawler
      dockerfile: Dockerfile
    environment:
      - JSON_PATH=/app/configs/
      - GRPC_PORT=:8000
    ports:
      - "8000"

  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CRAWLER_ADDRESS=crawler:8000
      - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200/
      - JSON_PATH=/app/configs/
      - DB_SOURCE=postgresql://root:secret@postgres:5432/footballnews?sslmode=disable
    depends_on:
      - crawler
      - elasticsearch
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/main"
      ]

