// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// AddTag provides a mock function with given fields: newTags
func (_m *MockTagRepository) AddTag(newTags string) error {
	ret := _m.Called(newTags)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(newTags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_AddTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTag'
type MockTagRepository_AddTag_Call struct {
	*mock.Call
}

// AddTag is a helper method to define mock.On call
//   - newTags string
func (_e *MockTagRepository_Expecter) AddTag(newTags interface{}) *MockTagRepository_AddTag_Call {
	return &MockTagRepository_AddTag_Call{Call: _e.mock.On("AddTag", newTags)}
}

func (_c *MockTagRepository_AddTag_Call) Run(run func(newTags string)) *MockTagRepository_AddTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTagRepository_AddTag_Call) Return(_a0 error) *MockTagRepository_AddTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_AddTag_Call) RunAndReturn(run func(string) error) *MockTagRepository_AddTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: tag
func (_m *MockTagRepository) DeleteTag(tag string) error {
	ret := _m.Called(tag)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagRepository_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockTagRepository_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - tag string
func (_e *MockTagRepository_Expecter) DeleteTag(tag interface{}) *MockTagRepository_DeleteTag_Call {
	return &MockTagRepository_DeleteTag_Call{Call: _e.mock.On("DeleteTag", tag)}
}

func (_c *MockTagRepository_DeleteTag_Call) Run(run func(tag string)) *MockTagRepository_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTagRepository_DeleteTag_Call) Return(_a0 error) *MockTagRepository_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_DeleteTag_Call) RunAndReturn(run func(string) error) *MockTagRepository_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function with given fields:
func (_m *MockTagRepository) ListTags() entities.Tags {
	ret := _m.Called()

	var r0 entities.Tags
	if rf, ok := ret.Get(0).(func() entities.Tags); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entities.Tags)
	}

	return r0
}

// MockTagRepository_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockTagRepository_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
func (_e *MockTagRepository_Expecter) ListTags() *MockTagRepository_ListTags_Call {
	return &MockTagRepository_ListTags_Call{Call: _e.mock.On("ListTags")}
}

func (_c *MockTagRepository_ListTags_Call) Run(run func()) *MockTagRepository_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTagRepository_ListTags_Call) Return(_a0 entities.Tags) *MockTagRepository_ListTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagRepository_ListTags_Call) RunAndReturn(run func() entities.Tags) *MockTagRepository_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockTagRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTagRepository(t mockConstructorTestingTNewMockTagRepository) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
