// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockPlayerRepository is an autogenerated mock type for the PlayerRepository type
type MockPlayerRepository struct {
	mock.Mock
}

type MockPlayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerRepository) EXPECT() *MockPlayerRepository_Expecter {
	return &MockPlayerRepository_Expecter{mock: &_m.Mock}
}

// FirstOrCreate provides a mock function with given fields: player
func (_m *MockPlayerRepository) FirstOrCreate(player *entities.Player) error {
	ret := _m.Called(player)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Player) error); ok {
		r0 = rf(player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type MockPlayerRepository_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - player *entities.Player
func (_e *MockPlayerRepository_Expecter) FirstOrCreate(player interface{}) *MockPlayerRepository_FirstOrCreate_Call {
	return &MockPlayerRepository_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", player)}
}

func (_c *MockPlayerRepository_FirstOrCreate_Call) Run(run func(player *entities.Player)) *MockPlayerRepository_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Player))
	})
	return _c
}

func (_c *MockPlayerRepository_FirstOrCreate_Call) Return(_a0 error) *MockPlayerRepository_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_FirstOrCreate_Call) RunAndReturn(run func(*entities.Player) error) *MockPlayerRepository_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockPlayerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPlayerRepository creates a new instance of MockPlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPlayerRepository(t mockConstructorTestingTNewMockPlayerRepository) *MockPlayerRepository {
	mock := &MockPlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
