// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockrepository

import (
	entities "server/entities"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockMatchDetailRepository is an autogenerated mock type for the MatchDetailRepository type
type MockMatchDetailRepository struct {
	mock.Mock
}

type MockMatchDetailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchDetailRepository) EXPECT() *MockMatchDetailRepository_Expecter {
	return &MockMatchDetailRepository_Expecter{mock: &_m.Mock}
}

// GetMatchDetail provides a mock function with given fields: date, club1Name, club2Name
func (_m *MockMatchDetailRepository) GetMatchDetail(date time.Time, club1Name string, club2Name string) (entities.MatchDetail, error) {
	ret := _m.Called(date, club1Name, club2Name)

	var r0 entities.MatchDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, string, string) (entities.MatchDetail, error)); ok {
		return rf(date, club1Name, club2Name)
	}
	if rf, ok := ret.Get(0).(func(time.Time, string, string) entities.MatchDetail); ok {
		r0 = rf(date, club1Name, club2Name)
	} else {
		r0 = ret.Get(0).(entities.MatchDetail)
	}

	if rf, ok := ret.Get(1).(func(time.Time, string, string) error); ok {
		r1 = rf(date, club1Name, club2Name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchDetailRepository_GetMatchDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchDetail'
type MockMatchDetailRepository_GetMatchDetail_Call struct {
	*mock.Call
}

// GetMatchDetail is a helper method to define mock.On call
//   - date time.Time
//   - club1Name string
//   - club2Name string
func (_e *MockMatchDetailRepository_Expecter) GetMatchDetail(date interface{}, club1Name interface{}, club2Name interface{}) *MockMatchDetailRepository_GetMatchDetail_Call {
	return &MockMatchDetailRepository_GetMatchDetail_Call{Call: _e.mock.On("GetMatchDetail", date, club1Name, club2Name)}
}

func (_c *MockMatchDetailRepository_GetMatchDetail_Call) Run(run func(date time.Time, club1Name string, club2Name string)) *MockMatchDetailRepository_GetMatchDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMatchDetailRepository_GetMatchDetail_Call) Return(_a0 entities.MatchDetail, _a1 error) *MockMatchDetailRepository_GetMatchDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchDetailRepository_GetMatchDetail_Call) RunAndReturn(run func(time.Time, string, string) (entities.MatchDetail, error)) *MockMatchDetailRepository_GetMatchDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchDetailsOnDayFromCrawler provides a mock function with given fields: matchURLs
func (_m *MockMatchDetailRepository) GetMatchDetailsOnDayFromCrawler(matchURLs entities.MatchURLsOnDay) {
	_m.Called(matchURLs)
}

// MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchDetailsOnDayFromCrawler'
type MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call struct {
	*mock.Call
}

// GetMatchDetailsOnDayFromCrawler is a helper method to define mock.On call
//   - matchURLs entities.MatchURLsOnDay
func (_e *MockMatchDetailRepository_Expecter) GetMatchDetailsOnDayFromCrawler(matchURLs interface{}) *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call {
	return &MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call{Call: _e.mock.On("GetMatchDetailsOnDayFromCrawler", matchURLs)}
}

func (_c *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call) Run(run func(matchURLs entities.MatchURLsOnDay)) *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.MatchURLsOnDay))
	})
	return _c
}

func (_c *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call) Return() *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call) RunAndReturn(run func(entities.MatchURLsOnDay)) *MockMatchDetailRepository_GetMatchDetailsOnDayFromCrawler_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockMatchDetailRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMatchDetailRepository creates a new instance of MockMatchDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMatchDetailRepository(t mockConstructorTestingTNewMockMatchDetailRepository) *MockMatchDetailRepository {
	mock := &MockMatchDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
