// Code generated by mockery v2.20.0. DO NOT EDIT.

package repository

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockOverviewItemRepository is an autogenerated mock type for the OverviewItemRepository type
type MockOverviewItemRepository struct {
	mock.Mock
}

type MockOverviewItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverviewItemRepository) EXPECT() *MockOverviewItemRepository_Expecter {
	return &MockOverviewItemRepository_Expecter{mock: &_m.Mock}
}

// FirstOrCreate provides a mock function with given fields: overviewItem
func (_m *MockOverviewItemRepository) FirstOrCreate(overviewItem *entities.OverviewItem) error {
	ret := _m.Called(overviewItem)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.OverviewItem) error); ok {
		r0 = rf(overviewItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOverviewItemRepository_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type MockOverviewItemRepository_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - overviewItem *entities.OverviewItem
func (_e *MockOverviewItemRepository_Expecter) FirstOrCreate(overviewItem interface{}) *MockOverviewItemRepository_FirstOrCreate_Call {
	return &MockOverviewItemRepository_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", overviewItem)}
}

func (_c *MockOverviewItemRepository_FirstOrCreate_Call) Run(run func(overviewItem *entities.OverviewItem)) *MockOverviewItemRepository_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OverviewItem))
	})
	return _c
}

func (_c *MockOverviewItemRepository_FirstOrCreate_Call) Return(_a0 error) *MockOverviewItemRepository_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOverviewItemRepository_FirstOrCreate_Call) RunAndReturn(run func(*entities.OverviewItem) error) *MockOverviewItemRepository_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockOverviewItemRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOverviewItemRepository creates a new instance of MockOverviewItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOverviewItemRepository(t mockConstructorTestingTNewMockOverviewItemRepository) *MockOverviewItemRepository {
	mock := &MockOverviewItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
