// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockOverviewItemServices is an autogenerated mock type for the OverviewItemServices type
type MockOverviewItemServices struct {
	mock.Mock
}

type MockOverviewItemServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverviewItemServices) EXPECT() *MockOverviewItemServices_Expecter {
	return &MockOverviewItemServices_Expecter{mock: &_m.Mock}
}

// FirstOrCreate provides a mock function with given fields: overviewItem
func (_m *MockOverviewItemServices) FirstOrCreate(overviewItem *entities.OverviewItem) error {
	ret := _m.Called(overviewItem)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.OverviewItem) error); ok {
		r0 = rf(overviewItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOverviewItemServices_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type MockOverviewItemServices_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - overviewItem *entities.OverviewItem
func (_e *MockOverviewItemServices_Expecter) FirstOrCreate(overviewItem interface{}) *MockOverviewItemServices_FirstOrCreate_Call {
	return &MockOverviewItemServices_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", overviewItem)}
}

func (_c *MockOverviewItemServices_FirstOrCreate_Call) Run(run func(overviewItem *entities.OverviewItem)) *MockOverviewItemServices_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OverviewItem))
	})
	return _c
}

func (_c *MockOverviewItemServices_FirstOrCreate_Call) Return(_a0 error) *MockOverviewItemServices_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOverviewItemServices_FirstOrCreate_Call) RunAndReturn(run func(*entities.OverviewItem) error) *MockOverviewItemServices_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockOverviewItemServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOverviewItemServices creates a new instance of MockOverviewItemServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOverviewItemServices(t mockConstructorTestingTNewMockOverviewItemServices) *MockOverviewItemServices {
	mock := &MockOverviewItemServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
