// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "server/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockStatsItemServices is an autogenerated mock type for the StatsItemServices type
type MockStatsItemServices struct {
	mock.Mock
}

type MockStatsItemServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsItemServices) EXPECT() *MockStatsItemServices_Expecter {
	return &MockStatsItemServices_Expecter{mock: &_m.Mock}
}

// FirstOrCreate provides a mock function with given fields: statsItem
func (_m *MockStatsItemServices) FirstOrCreate(statsItem *entities.StatisticsItem) error {
	ret := _m.Called(statsItem)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.StatisticsItem) error); ok {
		r0 = rf(statsItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStatsItemServices_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type MockStatsItemServices_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - statsItem *entities.StatisticsItem
func (_e *MockStatsItemServices_Expecter) FirstOrCreate(statsItem interface{}) *MockStatsItemServices_FirstOrCreate_Call {
	return &MockStatsItemServices_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", statsItem)}
}

func (_c *MockStatsItemServices_FirstOrCreate_Call) Run(run func(statsItem *entities.StatisticsItem)) *MockStatsItemServices_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.StatisticsItem))
	})
	return _c
}

func (_c *MockStatsItemServices_FirstOrCreate_Call) Return(_a0 error) *MockStatsItemServices_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStatsItemServices_FirstOrCreate_Call) RunAndReturn(run func(*entities.StatisticsItem) error) *MockStatsItemServices_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockStatsItemServices interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStatsItemServices creates a new instance of MockStatsItemServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStatsItemServices(t mockConstructorTestingTNewMockStatsItemServices) *MockStatsItemServices {
	mock := &MockStatsItemServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
